## Configuration file for CAVA.
# NOTE: This has comments removed since its a simplified version for waybar.
# See original file for full conf.

[general]

bars = 12
sleep_timer = 5

[input]


[output]

channels = stereo
method = raw
raw_target = /dev/stdout
waveform = 0
data_format = ascii
reverse = 1
bar_delimiter = 0

[color]

[smoothing]

[eq]
