# Style
inactive_text_alpha 1.0
hide_window_decorations yes
background_opacity 0.95
background_blur 20
cursor_trail 1
window_padding_width 5
enabled_layouts splits:split_axis=horizontal

# background transparency for nvim

# Behaviour
allow_remote_control yes
scrollback_lines 2000
copy_on_select yes
paste_actions quote-urls-at-prompt,confirm
strip_trailing_spaces smart
shell_integration enabled
confirm_os_window_close 0
editor nvim

# Tab bar
tab_bar_style       powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align center

# Keybinds
# Split panes
# For integration
allow_remote_control yes
listen_on unix:@mykitty

map ctrl+b>pipe       launch --location=vsplit --cwd=current
map ctrl+b>shift+5    launch --location=hsplit --cwd=current

map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l

# the 3 here is the resize amount, adjust as needed
map alt+down kitten relative_resize.py down  3
map alt+up kitten relative_resize.py up    3
map alt+left kitten relative_resize.py left  3
map alt+right kitten relative_resize.py right 3

map --when-focus-on var:IS_NVIM alt+j
map --when-focus-on var:IS_NVIM alt+k
map --when-focus-on var:IS_NVIM alt+h
map --when-focus-on var:IS_NVIM alt+l

# Tabs
map ctrl+b>c          launch --type=tab --cwd=current
map ctrl+b>n          next_tab
map ctrl+b>p          previous_tab
map ctrl+b>comma      set_tab_title
map ctrl+b>w          select_tab
map ctrl+b>ampersand  close_tab

# Close current pane
map ctrl+b>x          close_window

map ctrl+b>h          neighboring_window left
map ctrl+b>j          neighboring_window down
map ctrl+b>k          neighboring_window up
map ctrl+b>l          neighboring_window right

map ctrl+left  resize_window narrower 2
map ctrl+right resize_window wider 2
map ctrl+up    resize_window taller 2
map ctrl+down  resize_window shorter 2

map ctrl+shift+v paste_from_clipboard

map kitty_mod+f5 load_config_file

# BEGIN_KITTY_THEME
# Everforest Dark Medium
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="0xProto Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
font_size        13.0
